### PR TITLE
task-7-week-overlap-bug

### LINKED ISSUE #7: Weeks overlap for memory verse
The week should end on Saturday.

### PR DESCRIPTION
**Pull request by LonnyGomes**
An additional day was being adding. The perplexing bit was it was being intentionally done!

fixes #7

### CODE REVIEW

File: src/export.js [hunk 1]
```diff
@@ -94,8 +94,8 @@ class Exporter {
                 // determine end of week () which would be saturday
                 .endOf('week')
                 // the duration must go to the start of the new week
-                // sunday + monday === 2 days
-                .add(2, 'd');
+                // which is sunday
```
Comment (LonnyGomes) [inline src/export.js]: @LonnyGomes Two days were being added intentionally but that clearly doesn't get us what we want!

**Comment by LonnyGomes** [comment]
Another comment entered through the VSCode PR extention.
